# Generated by Django 6.0.2 on 2026-02-22 19:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('summary', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='این عنوان در نتایج گوگل نمایش داده می\u200cشود. (حدود ۶۰ کاراکتر)', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='این متن زیر عنوان در نتایج گوگل می\u200cآید. (حدود ۱۶۰ کاراکتر)', null=True)),
                ('og_image', models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک\u200cگذاری لینک نمایش داده می\u200cشود. (نسبت ۱.۹۱:۱)', null=True, upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='اگر این صفحه کپی صفحه\u200cی دیگری است، آدرس آن را وارد کنید.', null=True)),
                ('robots_index', models.BooleanField(default=True, help_text='اگر تیک نخورده باشد، به موتورهای جستجو می\u200cگوید این صفحه را ایندکس نکنند (noindex).')),
                ('robots_follow', models.BooleanField(default=True, help_text='اگر تیک نخورده باشد، به موتورهای جستجو می\u200cگوید لینک\u200cهای این صفحه را دنبال نکنند (nofollow).')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('alt_image', models.CharField(blank=True, max_length=255, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('author', models.CharField(default='Arsene Team', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='این عنوان در نتایج گوگل نمایش داده می\u200cشود. (حدود ۶۰ کاراکتر)', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='این متن زیر عنوان در نتایج گوگل می\u200cآید. (حدود ۱۶۰ کاراکتر)', null=True)),
                ('og_image', models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک\u200cگذاری لینک نمایش داده می\u200cشود. (نسبت ۱.۹۱:۱)', null=True, upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='اگر این صفحه کپی صفحه\u200cی دیگری است، آدرس آن را وارد کنید.', null=True)),
                ('robots_index', models.BooleanField(default=True, help_text='اگر تیک نخورده باشد، به موتورهای جستجو می\u200cگوید این صفحه را ایندکس نکنند (noindex).')),
                ('robots_follow', models.BooleanField(default=True, help_text='اگر تیک نخورده باشد، به موتورهای جستجو می\u200cگوید لینک\u200cهای این صفحه را دنبال نکنند (nofollow).')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('alt_image', models.CharField(blank=True, max_length=255, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
